"""empty message

Revision ID: 28a92bdfe34a
Revises: 629edf176c81
Create Date: 2020-07-23 17:26:52.719694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28a92bdfe34a'
down_revision = '629edf176c81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('displaylimit', sa.String(), nullable=True))
    op.add_column('data', sa.Column('totalexceed', sa.Integer(), nullable=True))
    op.drop_column('data', 'completed')
    op.drop_column('data', 'carb_content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('carb_content', sa.INTEGER(), nullable=True))
    op.add_column('data', sa.Column('completed', sa.INTEGER(), nullable=True))
    op.drop_column('data', 'totalexceed')
    op.drop_column('data', 'displaylimit')
    # ### end Alembic commands ###
