"""empty message

Revision ID: 4ae2b14cd321
Revises: 
Create Date: 2020-07-20 23:09:17.097622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae2b14cd321'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('carb_content', sa.Integer(), nullable=True))
    op.add_column('data', sa.Column('fat', sa.Integer(), nullable=False))
    op.add_column('data', sa.Column('protien', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'data', ['protien'])
    op.create_unique_constraint(None, 'data', ['carb_content'])
    op.drop_column('data', 'completed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('completed', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'data', type_='unique')
    op.drop_constraint(None, 'data', type_='unique')
    op.drop_column('data', 'protien')
    op.drop_column('data', 'fat')
    op.drop_column('data', 'carb_content')
    # ### end Alembic commands ###
